# Generated by Django 5.2.7 on 2025-11-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0002_reports_alter_menu_picture_alter_table_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettingsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('menu_display_style', models.CharField(default='grid', max_length=50)),
                ('menu_theme_color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
    ]
