# Generated by Django 5.2.7 on 2025-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0003_hotelsettingspreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='Category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reports',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
