# Generated by Django 5.2.7 on 2025-11-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0004_remove_category_id_remove_menu_id_remove_orders_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelSettingsPreferences',
            new_name='HotelSettings',
        ),
    ]
