# Generated by Django 5.2.7 on 2025-11-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0005_rename_hotelsettingspreferences_hotelsettings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelsettings',
            table='hotel_settings',
        ),
    ]
