# Generated by Django 5.2.7 on 2025-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0006_alter_hotelsettings_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsettings',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
