# Generated by Django 5.2.7 on 2025-11-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0007_alter_hotelsettings_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelsettings',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='operating_hours',
            field=models.CharField(default='09:00 - 22:00', max_length=100),
        ),
    ]
