# Generated by Django 5.2.7 on 2025-11-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0008_remove_hotelsettings_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='auto_mark_table_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='auto_qr_code_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='table_section',
            field=models.CharField(default='Indoor', max_length=100),
        ),
    ]
