# Generated by Django 5.2.7 on 2025-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0009_hotelsettings_auto_mark_table_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
