# Generated by Django 5.2.8 on 2025-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0010_menu_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='InbuiltMenuItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='inbuilt_menus/')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inbuilt_menu_items',
            },
        ),
    ]
