# Generated by Django 5.2.8 on 2025-11-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0011_inbuiltmenuitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_id',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
