# Generated by Django 5.2.8 on 2025-12-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0012_rename_category_id_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbuiltmenuitems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_flow.category'),
        ),
    ]
