# Generated by Django 5.2.9 on 2025-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0013_alter_inbuiltmenuitems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('M-PESA', 'M-PESA')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
