# Generated by Django 5.2.9 on 2025-12-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0014_orders_payment_method_orders_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
