# Generated by Django 5.2.9 on 2025-12-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0015_orders_payment_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
    ]
