# Generated by Django 5.2.9 on 2025-12-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0016_order_orderitem_delete_orders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
