# Generated by Django 5.2.9 on 2026-01-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0016_alter_orders_options_alter_orders_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
