# Generated by Django 5.2.9 on 2026-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0019_order_mpesa_amount_order_mpesa_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('VERIFYING', 'Verifying'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
