# Generated by Django 5.2.9 on 2026-01-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0022_maincategory_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
    ]
