# Generated by Django 5.2.9 on 2026-01-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0024_category_main_category'),
        ('common_flow', '0024_merge_20260106_1016'),
    ]

    operations = [
    ]
