# Generated by Django 5.2.9 on 2026-01-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0025_merge_20260111_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='common_flow.maincategory'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
