# Generated by Django 5.2.9 on 2026-01-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0026_alter_category_main_category_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='common_flow.maincategory'),
        ),
    ]
