# Generated by Django 5.2.9 on 2026-01-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0027_alter_category_main_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
