# Generated by Django 5.2.9 on 2026-01-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0028_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT_TO_KITCHEN', 'Sent to Kitchen'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
