# Generated by Django 5.2.9 on 2026-01-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0027_alter_category_main_category_alter_order_status'),
        ('common_flow', '0029_alter_order_status'),
    ]

    operations = [
    ]
