# Generated by Django 5.2.9 on 2026-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0030_paymentattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
