# Generated by Django 5.2.9 on 2026-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0030_merge_20260129_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT_TO_KITCHEN', 'Sent to Kitchen'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('READY', 'Ready')], default='PENDING', max_length=20),
        ),
    ]
