# Generated by Django 5.2.9 on 2026-02-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0027_alter_category_main_category_alter_order_status'),
        ('common_flow', '0031_delete_paymentattempt'),
    ]

    operations = [
    ]
