# Generated by Django 5.2.9 on 2026-02-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_flow', '0031_alter_order_status'),
        ('common_flow', '0032_merge_20260205_1352'),
    ]

    operations = [
    ]
