# Generated by Django 5.2.9 on 2026-01-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=100)),
                ('account_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_admin_flow.hoteltenant')),
            ],
            options={
                'db_table': 'payment_index',
                'indexes': [models.Index(fields=['order_ref'], name='payment_ind_order_r_1e32cc_idx'), models.Index(fields=['account_reference'], name='payment_ind_account_8ea4f5_idx'), models.Index(fields=['checkout_request_id'], name='payment_ind_checkou_40bdd5_idx')],
            },
        ),
    ]
