# Generated by Django 5.2.9 on 2026-02-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_flow', '0002_paymentindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('seat', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_data', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_admin_flow.hoteltenant')),
            ],
            options={
                'db_table': 'payment_attempts',
                'indexes': [models.Index(fields=['reference'], name='payment_att_referen_ca3d84_idx'), models.Index(fields=['phone_number'], name='payment_att_phone_n_cd8d12_idx'), models.Index(fields=['status'], name='payment_att_status_34eb7e_idx')],
            },
        ),
    ]
