# Generated by Django 5.2.9 on 2026-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_flow', '0003_paymentattempt'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='payment_att_referen_ca3d84_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='payment_att_phone_n_cd8d12_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='payment_att_status_34eb7e_idx',
        ),
    ]
