# Generated by Django 5.2.9 on 2026-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_flow', '0004_remove_paymentattempt_payment_att_referen_ca3d84_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
