apiVersion: v1
kind: Service
metadata:
  name: smart-hotel-service
  labels:
    app: smart-hotel
spec:
  selector:
    app: smart-hotel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP