name: Smart_Hotel_system CI/CD Pipeline
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    
jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r smart_hotel_system/requirements.txt
        # - name: Run tests
        #   run: |
        #     cd smart_hotel_system
        #     python manage.py test smart_hotel_system.tests

    frontend:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install dependencies
          run: |
            cd smart_hotel_system
            npm install
        # - name: Run tests
        #   run: |
        #     cd frontend
        #     npm test
        # pip freeze > requirements.txt